version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - go

  - package-ecosystem: npm
    directory: /web/recipient
    schedule:
      interval: weekly
    labels:
      - dependencies
      - frontend
